import { ColorSchemeScript, MantineProvider } from '@mantine/core';

import { resolver } from './theme/createResolver';
import { theme } from './theme/createTheme';

import '@mantine/core/styles.css';
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => (
  <html lang="en">
    <head>
      <ColorSchemeScript />
      <link rel="stylesheet" href="https://use.typekit.net/thx0pbt.css" />
    </head>

    <body>
      <MantineProvider
        cssVariablesResolver={resolver}
        defaultColorScheme="auto"
        theme={theme}
      >
        {children}
      </MantineProvider>
    </body>
  </html>
);

export default RootLayout;
