export const DATA = [
  {
    src: '/home-hero-1.jpg',
    width: 80,
    height: 60,
    name: 'Hailey Wagner',
    username: 'haileyellenw',
    url: 'https://unsplash.com/photos/white-and-pink-flowers-on-brown-wooden-box-4icV47LjYc4',
  },
  {
    src: '/home-hero-2.jpg',
    width: 80,
    height: 80,
    name: 'Dan Gold',
    username: 'danielcgold',
    url: 'https://unsplash.com/photos/four-person-earring-on-black-wooden-table-E6HjQaB7UEA',
  },
  {
    src: '/home-hero-3.jpg',
    width: 80,
    height: 80,
    name: 'Solé Bicycles',
    username: 'solebicycles',
    url: 'https://unsplash.com/photos/blue-and-yellow-road-bike-LPVMzMsO51o',
  },
  {
    src: '/home-hero-4.jpg',
    width: 80,
    height: 80,
    name: 'Nimble Made',
    username: 'nimblemade',
    url: 'https://unsplash.com/photos/black-and-orange-nike-polo-shirt-N0ke5zChVBU',
  },
  {
    src: '/demo-1.jpg',
    width: 80,
    height: 54,
    name: 'eniko kis',
    username: 'enikoo',
    url: 'https://unsplash.com/photos/stack-of-3-black-white-bowls-L0g_gTN8l_A',
  },
  {
    src: '/demo-2.jpg',
    width: 80,
    height: 54,
    name: 'S O C I A L . C U T',
    username: 'socialcut',
    url: 'https://unsplash.com/photos/assorted-colored-clothes-on-rack-near-brown-wooden-table-7KkDiSs5UdQ',
  },
  {
    src: '/demo-3.jpg',
    width: 80,
    height: 54,
    name: 'Mel Poole',
    username: 'melpoole',
    url: 'https://unsplash.com/photos/white-blue-and-red-stars-print-textile-i6NcIJXdK10',
  },
  {
    src: '/demo-4.jpg',
    width: 80,
    height: 54,
    name: 'Rachel Park',
    username: 'therachelstory',
    url: 'https://unsplash.com/photos/round-white-ceramic-plate-filled-with-waffle-hrlvr2ZlUNk',
  },
  {
    src: '/demo-5.jpg',
    width: 80,
    height: 54,
    name: 'Curology',
    username: 'curology',
    url: 'https://unsplash.com/photos/three-assorted-toiletries-on-brown-shelf-ZWNO4bzUP7k',
  },
  {
    src: '/demo-6.jpg',
    width: 80,
    height: 54,
    name: 'Becca Tapert',
    username: 'beccatapert',
    url: 'https://unsplash.com/photos/orange-ceramic-container-Nx_6-BQ0X6o',
  },
  {
    src: '/demo-7.jpg',
    width: 80,
    height: 54,
    name: 'Yours',
    username: 'lovefromyours',
    url: 'https://unsplash.com/photos/white-and-pink-hair-brush-on-glass-table-B9EHePG56zA',
  },
  {
    src: '/demo-9-slide-1.jpg',
    width: 80,
    height: 54,
    name: 'Alejandro Escamilla',
    username: 'alejandroescamilla',
    url: 'https://unsplash.com/',
  },
  {
    src: '/demo-9-slide-2.jpg',
    width: 80,
    height: 54,
    name: 'Jakob Owens',
    username: 'jakobowens1',
    url: 'https://unsplash.com/photos/assorted-camera-film-cartridges-qQdv-By21yE',
  },
  {
    src: '/demo-9-slide-3.jpg',
    width: 80,
    height: 54,
    name: 'KAL VISUALS',
    username: 'kalvisuals',
    url: 'https://unsplash.com/',
  },
];
